# Generated by Django 4.0.6 on 2022-07-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='owner',
        ),
    ]
